### ISSUE TITLE
Deskpi Super6c USB ports not working

### ISSUE THREAD

**Issue by ouziel-slama** [towercomputers/toweros#111]

**Comment by ouziel-slama** [comment]
`dmesg | grep usb`:

```
[    1.527450] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    1.527641] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.15
[    1.527660] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.527673] usb usb2: Product: xHCI Host Controller
[    1.527685] usb usb2: Manufacturer: Linux 5.15.105-0-rpi4 xhci-hcd
[    1.527697] usb usb2: SerialNumber: fe9c0000.xhci
```

**Comment by adamkrellenstein** [comment]
@ouziel-slama you said that the problem was resolved by flashing the CM4 bootloader or something like that?

**Comment by ouziel-slama** [comment]
yes given that it works well with certain CM4s I am fairly sure that it comes from the bootloader. The deskpi's micro-USBs are too fragile, I ordered a CM4 board to test updating the bootloader of a CM4...

**Comment by ouziel-slama** [comment]
unfortunately this does not solve the problem :-/
I just updated the CM4's eeprom and it still doesn't work for this CM4! I compiled the master branch from https://github.com/raspberrypi/usbboot so I'm sure to have the latest version! (btw I didn't manage to do it on the Lenovo but only on the Mac, probably a USB port problem...). I'll keep looking but no real ideas.

**Comment by adamkrellenstein** [comment]
Have you not heard back from customer support? We bought these devices from a company—they should help us get it to work!

**Comment by adamkrellenstein** [comment]
Also have you tried other OSs?

**Comment by ouziel-slama** [comment]
> Have you not heard back from customer support? We bought these devices from a company—they should help us get it to work!

nope! two emails and no answers!

> Also have you tried other OSs?

yep! and several version!
just miss to test the cm4 with another board ! waiting a mini nvme ssd to test with the board I used to update the eeprom.

**Comment by ouziel-slama** [comment]
(this one https://www.amazon.com/BIGTREETECH-Pi4B-Raspberry-Compatible-Supports/dp/B0B82MH21K)

**Comment by ouziel-slama** [comment]
Moving to 0.6.0!

**Comment by ouziel-slama** [comment]
some more tests:
- the USB does not work on another board.
- of the 6 cm4 that I have there is only the one with wifi whose USB does not work.
I don't have any other CM4s with wifi to know if this particular CM4 has a problem or all the CM4s with wifi.

**Comment by ouziel-slama** [comment]
Just ordered a CM4102000! let's hope it works well!

**Comment by ouziel-slama** [comment]
Works well with the  CM4 I just received from Welectron! So it's just a broken a CM4 :/
